import feedparser
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity
from datetime import datetime
import os

# --- USER PROFILES ---
USERS = {
    "Alex Parker": {
        "interests": ["AI", "cybersecurity", "blockchain", "startups", "programming"],
        "feeds": [
            "https://techcrunch.com/feed/",
            "https://www.wired.com/feed/category/tech/latest/rss",
            "https://arstechnica.com/feed/",
            "https://www.technologyreview.com/feed/"
        ]
    },
    "Priya Sharma": {
        "interests": ["global markets", "startups", "fintech", "cryptocurrency", "economics"],
        "feeds": [
            "https://www.bloomberg.com/feed/podcast/etf-report.xml",
            "https://www.ft.com/?format=rss",
            "https://www.forbes.com/markets/feed/",
            "https://www.coindesk.com/arc/outboundfeeds/rss/"
        ]
    },
    "Marco Rossi": {
        "interests": ["football", "F1", "NBA", "Olympic sports", "esports"],
        "feeds": [
            "https://www.espn.com/espn/rss/news",
            "http://feeds.bbci.co.uk/sport/rss.xml",
            "https://www.skysports.com/rss/12040",
            "https://theathletic.com/feed/"
        ]
    },
    "Lisa Thompson": {
        "interests": ["movies", "celebrity news", "TV shows", "music", "books"],
        "feeds": [
            "https://variety.com/feed/",
            "https://www.rollingstone.com/music/music-news/feed/",
            "https://www.billboard.com/feed/",
            "https://www.hollywoodreporter.com/t/feed/"
        ]
    },
    "David Martinez": {
        "interests": ["space exploration", "AI", "biotech", "physics", "renewable energy"],
        "feeds": [
            "https://www.nasa.gov/rss/dyn/breaking_news.rss",
            "https://www.sciencedaily.com/rss/all.xml",
            "https://www.nature.com/subjects/technology/rss",
            "https://feeds.arstechnica.com/arstechnica/science"
        ]
    }
}

# --- FETCH ARTICLES FROM RSS ---
def fetch_articles(feed_urls, max_articles=30):
    articles = []
    for url in feed_urls:
        feed = feedparser.parse(url)
        for entry in feed.entries[:max_articles]:
            articles.append({
                "title": entry.title,
                "link": entry.link,
                "summary": entry.get("summary", entry.get("description", "")),
                "published": entry.get("published", "Unknown")
            })
    return articles

# --- COMPUTE ARTICLE RELEVANCE ---
def compute_scores(articles, interests):
    content = [article['title'] + " " + article['summary'] for article in articles]
    vectorizer = TfidfVectorizer(stop_words='english')
    tfidf_matrix = vectorizer.fit_transform(content)
    interest_query = vectorizer.transform([" ".join(interests)])
    scores = cosine_similarity(tfidf_matrix, interest_query).flatten()
    return scores

# --- GENERATE MARKDOWN NEWSLETTER ---
def generate_markdown(user_name, interests, articles, scores, top_n=10):
    today = datetime.now().strftime("%Y-%m-%d")
    # Create folder 'newsletters' if it doesn't exist
    folder_path = os.path.join(os.getcwd(), "newsletters")
    if not os.path.exists(folder_path):
        os.makedirs(folder_path)
    
    filename = os.path.join(folder_path, f"{user_name.replace(' ', '_')}_Newsletter_{today}.md")

    top_articles = sorted(zip(articles, scores), key=lambda x: x[1], reverse=True)[:top_n]

    with open(filename, "w", encoding="utf-8") as f:
        f.write(f"# Personalized Newsletter for {user_name}\n")
        f.write(f"Date: {today}\n\n")
        f.write(f"Top Interests: {', '.join(interests)}\n\n")
        f.write("Highlights:\n")

        for i, (article, score) in enumerate(top_articles, 1):
            f.write(f"{i}. {article['title']}\n")
            f.write(f"Published: {article['published']}\n\n")
            f.write(f"{article['summary'][:300]}...\n\n")
            f.write(f"[Read Full Article]({article['link']})\n\n")

        f.write("\n---\nGenerated by an AI-Powered Newsletter System using TF-IDF magic!")

    return filename

# --- MAIN DRIVER FUNCTION ---
def generate_for_all_users():
    for user_name, user_profile in USERS.items():
        print(f"\nGenerating newsletter for {user_name}...")
        articles = fetch_articles(user_profile["feeds"])
        scores = compute_scores(articles, user_profile["interests"])
        md_file = generate_markdown(user_name, user_profile["interests"], articles, scores)
        print(f"Newsletter saved: {md_file}")

# --- RUN FOR ALL USERS ---
if __name__ == "__main__":
    generate_for_all_users()
